return {
    CornerRoundness = UDim.new(0, 20),
    WindowColor = Color3.fromRGB(20, 20, 20),
    ShadowColor = Color3.fromRGB(20, 20, 20),

    ElementColor = Color3.fromRGB(30, 30, 30),
    ElementStroke = Color3.fromRGB(35, 35, 35),
    DividerColor = Color3.fromRGB(255, 255, 255),
    TabColor = Color3.fromRGB(255, 255, 255),
    ActionColor = Color3.fromRGB(255, 255, 255),
    TitleFont = Font.new("rbxassetid://12187365364", Enum.FontWeight.SemiBold),
    Font = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium),
    ContentColor = Color3.fromRGB(255, 255, 255),

    LiveAnimation = false, -- Subtly changes window gradient and shadow offset to make Rayfield feel more natural.

    DarkToggleOverlay = true,
    ElementTransparency = 0,
    ElementStrokeTransparency = 0,
    ElementHoverTransparency = 0,
    ElementStrokeHoverTransparency = 0,
    ElementHoverColor = Color3.fromRGB(35, 35, 35),
    ElementStrokeHover = Color3.fromRGB(50, 50, 50),
    ElementStrokeHoverColor = Color3.fromRGB(50, 50, 50),
    ElementCornerRadius = UDim.new(0, 12),
    ElementTextHoverColor = Color3.fromRGB(255, 255, 255),
    ElementContentHoverColor = Color3.fromRGB(255, 255, 255),
    TitlingColor = Color3.fromRGB(255, 255, 255),

    ErrorColor = Color3.fromRGB(110, 0, 0),
    ErrorStrokeColor = Color3.fromRGB(140, 0, 0)
}