return {
    CornerRoundness = UDim.new(0, 20),
    WindowColor = Color3.fromRGB(20, 20, 20),

    ElementColor = Color3.fromRGB(30, 30, 30),
    ElementStroke = Color3.fromRGB(35, 35, 35),
    DividerColor = Color3.fromRGB(255, 255, 255),
    TabColor = Color3.fromRGB(255, 255, 255),
    ActionColor = Color3.fromRGB(255, 255, 255),
    Font = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium),
    TextColor = Color3.fromRGB(255, 255, 255),
}