return {
    CornerRoundness = UDim.new(0, 0),
    WindowColor = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 89, 212)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(38, 148, 117)),
    }),
    ShadowColor = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 89, 212)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(38, 148, 117)),
    }),

    DividerColor = Color3.fromRGB(255, 255, 255),

    TabColor = Color3.fromRGB(255, 255, 255)
}