name: CI
permissions:
  contents: read
on:
  push:

jobs:
  check:
    name: Lint, Format, Typecheck and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.2.1

      - name: Install RoKit packages
        run: make install

      - name: Required checks
        run: make ci
