name: CI
permissions:
  contents: write
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  check:
    name: Lint, Format, Typecheck and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install RoKit packages
        run: make install

      - name: Format, lint, typecheck and test
        run: make ci

  build_and_bundle:
    name: Bundle and Publish Rayfield Gen2 Release
    needs: check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Read Version
        id: version
        run: |
          VERSION="$(cat version.txt)"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "SKIP=true" >> $GITHUB_OUTPUT
          else
            echo "SKIP=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup RoKit
        if: steps.version.outputs.SKIP == 'false'
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install RoKit packages
        if: steps.version.outputs.SKIP == 'false'
        run: |
          rokit trust rojo-rbx/rojo
          rokit trust lune-org/lune
          rokit trust seaofvoices/darklua
          rokit trust JohnnyMorganz/StyLua
          rokit trust Kampfkarren/selene
          rokit trust JohnnyMorganz/luau-lsp
          rokit install

      - name: Bundle
        if: steps.version.outputs.SKIP == 'false'
        run: lune run wax bundle output="build/bundled.luau" input="wax.project.json" minify=true

      - name: Finalise Release, Publish
        if: steps.version.outputs.SKIP == 'false'
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/bundled.luau
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ steps.version.outputs.VERSION }}"
          name: "Rayfield Gen2 ${{ steps.version.outputs.VERSION }}"
