# Nearly copy and pasted from
# https://github.com/ActualMasterOogway/Fluent-Renewed/tree/main
# (Thanks oogway <3)

name: Pushed
permissions:
    contents: write
on:
    push:
        paths:
            - '**.luau'
            - '**.lua'
            - '**.rbxm'
            - '**.json'
            - '**.yml'
    pull_request:
        paths:
            - '**.luau'
            - '**.lua'
            - '**.rbxm'
            - '**.json'
            - '**.yml'

jobs:
    build_and_bundle:
        name: Generate UI release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Setup RoKit
              uses: CompeyDev/setup-rokit@v0.1.2

            - name: Install RoKit packages
              run: |
                  rokit trust rojo-rbx/rojo
                  rokit trust lune-org/lune
                  rokit trust seaofvoices/darklua
                  rokit install
    
            - name: Build and bundle project
              run: lune run wax bundle output="build/bundled.luau" input="wax.project.json" minify=true darklua-config-path=".lune/DarkLua.json"

            - name: Upload Bundled File to Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: bundled.luau
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.run_id }}
                  name: Automatic Release
