name: Release Bundle

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build_and_upload:
    name: Build and Upload Release Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          submodules: true

      - name: Setup RoKit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Install RoKit packages
        run: make install

      - name: Bundle
        run: make bundle

      - name: Upload bundle to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: gh release upload "$RELEASE_TAG" build/bundled.luau --clobber
